// src/app/components/footer/footer.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-footer',
  templateUrl: './footer.component.html',
  styleUrls: ['./footer.component.scss']
})
export class FooterComponent {
  day = 21;
  month = 'December';
  year = 2020;
}

<div class="footer">
  <p>
    Email at
    <a href="mailto: pauljscott8@gmail.com" target="_blank"
      >pauljscott8@gmail.com</a
    >
    or call at (215) 880-9592
  </p>
  <p>Created using Angular</p>
  <p>Last updated February 5<sup>th</sup>, 2023</p>
</div>

// app/components/footer/footer.tsx
import styles from "./footer.module.scss";

export default function Footer() {
  return (
    <footer className={styles.footer}>
      Email at <a href="mailto:pauljscott8@gmail.com">pauljscott8@gmail.com</a>{" "}
      or call at (215) 880-9592
      <br />
      Updated December 30<sup>th</sup>, 2024
    </footer>
  );
}
