// app/components/header/header.tsx
import styles from "./header.module.css";

export default function Header() {
  return (
    <header className={styles.header}>
      <img src="imgs/header/logo.svg"></img>
      <nav className={styles.nav}>
        <a href="#experience">Experience</a>
        <a href="#skills">Skills</a>
        <a href="#education">Education</a>
        <a href="#projects">Projects</a>
        <a href="#hobbies">Hobbies</a>
        <div className={styles.verticalSeparator}></div>
        <a href="mailto:pauljscott8@gmail.com" target="_blank"><img src="imgs/header/email.svg"/></a>
        <a href="https://drive.google.com/file/d/181m4g11n53sekOgt40T1ZhLruRoqN56X/view?usp=sharing" target="_blank"><img src="imgs/header/resume.svg"/></a>
        <a href="https://www.linkedin.com/in/paul-scott-047858140/" target="_blank"><img src="imgs/header/linkedin.svg"/></a>
        <a href="https://github.com/PScottZero" target="_blank"><img src="imgs/header/github.svg"/></a>
      </nav>
    </header>
  );
}

// src/app/components/header/header.component.ts
import { Component, HostListener, OnInit } from '@angular/core';
import { IconButton } from '../icon-button/IconButton';

@Component({
  selector: 'app-header',
  templateUrl: './header.component.html',
  styleUrls: ['./header.component.scss'],
})
export class HeaderComponent implements OnInit {
  buttons = [
    new IconButton('email.svg', 'mailto: pauljscott8@gmail.com'),
    new IconButton(
      'resume.svg',
      'https://drive.google.com/file/d/1bEgXA6MulpzrJsdV27eBeltPN27pp7pk/view?usp=sharing'
    ),
    new IconButton(
      'linkedin.svg',
      'https://www.linkedin.com/in/paul-scott-047858140/'
    ),
    new IconButton('github.svg', 'https://github.com/PScottZero'),
  ];
  menuIsVisible: boolean;

  ngOnInit(): void {
    this.menuIsVisible = false;
  }

  toggleMenu(): void {
    this.menuIsVisible = !this.menuIsVisible;
    const header = document.getElementById('header');
    header.classList.add('header-scroll');
    if (window.pageYOffset <= 0 && !this.menuIsVisible) {
      header.classList.remove('header-scroll');
    }
  }

  @HostListener('window:scroll', ['$event'])
  onScroll(): void {
    const header = document.getElementById('header');
    if (window.scrollY > 0 || this.menuIsVisible) {
      header.classList.add('header-scroll');
    } else {
      header.classList.remove('header-scroll');
    }
  }
}

<header id="header" [class.header_with_menu]="menuVisible()">

  <!-- logo -->
  <img src="../../../assets/img/main/logo.svg" alt="Paul Scott">

  <div class="menu_icon" (click)="toggleMenu()">
    <div class="menu_icon_bar" [class.rotate]="menuVisible()"></div>
    <div class="menu_icon_bar" [class.rotate]="menuVisible()"></div>
  </div>

  <!-- links -->
  <nav [class.menu_height]="menuVisible()">
    <a (click)="showAboutData()">About Me</a>
    <a (click)="showProjectData()">Projects</a>
    <a href="https://drive.google.com/open?id=1Z79TNs30ttAftoWwJbqm93X77OljiM3L" target="_blank" (click)="closeMenu()">Resume</a>
    <a href="https://www.linkedin.com/in/paul-scott-047858140/" target="_blank" (click)="closeMenu()">LinkedIn</a>
    <a href="https://github.com/PScottZero" target="_blank" (click)="closeMenu()">GitHub</a>
  </nav>
</header>
