// app/components/card/card.tsx
"use client";

import Image from "next/image";
import styles from "./card.module.scss";
import variables from "../../constants.module.scss";

export type CardData = {
  title: string;
  description?: string | string[];
  image: string;
  link?: string;
};

export class CardDims {
  width: string = "";
  titleSize: string = "";
  descriptionSize: string = "";
  labelPadding: string = "";
}

export type CardProps = {
  data: CardData;
  dims: CardDims;
  imageFolder: string;
};

export default function Card({ data, dims, imageFolder }: CardProps) {
  let descriptionLines = [];
  if (data.description !== undefined) {
    if (Array.isArray(data.description)) {
      for (let i = 0; i < data.description.length; i++) {
        descriptionLines.push(<p key={i}>{data.description[i]}</p>);
      }
    } else {
      descriptionLines.push(<p key={0}>{data.description}</p>);
    }
  }

  const hasLink = data.link !== undefined;
  const linkStyles = hasLink ? styles.link : "";
  const linkFn = hasLink ? () => window.open(data.link) : undefined;
  const linkIcon = hasLink ? (
    <Image
      className={styles.linkIcon}
      src="icons/link.svg"
      alt="link"
      width={64}
      height={64}
    />
  ) : undefined;

  const cardStyles = `${styles.card} ${linkStyles}`;
  return (
    <div
      style={{ flex: dims.width, maxWidth: dims.width }}
      className={cardStyles}
      onClick={linkFn}
    >
      <div className={styles.label} style={{ padding: dims.labelPadding }}>
        <div className={styles.title} style={{ fontSize: dims.titleSize }}>
          {data.title}
        </div>
        <div
          className={styles.description}
          style={{ fontSize: dims.descriptionSize }}
        >
          {descriptionLines}
          {linkIcon}
        </div>
      </div>
      <Image
        className={styles.image}
        src={"/images/" + imageFolder + "/" + data.image}
        alt={data.title}
        width={512}
        height={512}
      />
    </div>
  );
}

// src/lib/components/card.svelte
<script module lang="ts">
	export type CardData = {
		title: string;
		description?: string | string[];
		image: string;
		link?: string;
	};

	export class CardDims {
		width: string = '';
		titleSize: string = '';
		descriptionSize: string = '';
		labelPadding: string = '';
	}

	type CardProps = {
		data: CardData;
		dims: CardDims;
		imageFolder: string;
	};
</script>

<script lang="ts">
	let { data, dims, imageFolder }: CardProps = $props();

	const hasLink = data.link !== undefined;

	const descriptionLines: string[] = [];
	if (data.description !== undefined) {
		if (Array.isArray(data.description)) {
			for (const line of data.description) {
				descriptionLines.push(line);
			}
		} else {
			descriptionLines.push(data.description);
		}
	}
</script>

<button
	class="card {hasLink ? 'link' : ''}"
	style:flex={dims.width}
	style:max-width={dims.width}
	onclick={hasLink ? () => window.open(data.link) : undefined}
>
	<div class="label" style:padding={dims.labelPadding}>
		<div class="title" style:font-size={dims.titleSize}>
			{data.title}
		</div>
		<div class="description" style:font-size={dims.descriptionSize}>
			{#each descriptionLines as line, i (i)}
				<p>{line}</p>
			{/each}
			{#if hasLink}
				<img class="link-icon" src="icons/link.svg" alt="link" />
			{/if}
		</div>
	</div>
	<img
		class="image"
		src="/images/{imageFolder}/{data.image}"
		alt={data.title}
	/>
</button>

<style lang="scss">
	@use '$lib/scss/colors.scss' as c;
	@use '$lib/scss/mixins.scss' as m;
	@use '$lib/scss/variables.scss' as v;

	.card {
		@include m.content-border;
		position: relative;
		aspect-ratio: 4/3;
		overflow: hidden;
		font-family: inherit;
		background-color: c.$menu-color;
	}

	.label {
		position: absolute;
		bottom: 0;
		width: 100%;
		padding: 1rem;
		background-color: rgba(c.$content-color, 0.85);
		border-top: v.$border-size solid c.$content-border-color1;
	}

	.title {
		font-size: v.$large-font-size;
		font-weight: bold;
	}

	.description {
		position: relative;
		font-size: v.$medium-font-size;
	}

	.image {
		width: 100%;
		height: 100%;
		object-fit: cover;
	}

	.link:hover {
		@include m.double-border(
			c.$content-border-color2,
			c.$content-border-color1
		);
		cursor: pointer;
	}

	.link-icon {
		position: absolute;
		width: 1rem;
		right: 0;
		bottom: 0;
	}
</style>
